export const IS_LOGGED = {
    FALSE: false,
    TRUE: true
}
export const AUTH_STATE = {
    LOADING: "LOADING",
    SUCCES: "SUCCESS",
    FAILURE: "FAILURE"
}
export const USER_LOAD = {
    USER_LOAD_REQUEST: "USER_LOAD_REQUEST",
    USER_LOAD_SUCCESS: "USER_LOAD_SUCCESS",
    USER_LOAD_FAILURE: "USER_LOAD_FAILURE"
}
export const USER_LOGOUT = {
    USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE"
}