export const ADD_PRODUCT = {
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE"
}
export const REMOVE_PRODUCT = {
    REMOVE_PRODUCT_REQUEST: "REMOVE_PRODUCT_REQUEST",
    REMOVE_PRODUCT_SUCCESS: "REMOVE_PRODUCT_SUCCESS",
    REMOVE_PRODUCT_FAILURE: "REMOVE_PRODUCT_FAILURE"
}
export const SET_CART = {
    SET_CART_REQUEST: "SET_CART_REQUEST",
    SET_CART_SUCCESS: "SET_CART_SUCCESS",
    SET_CART_FAILURE: "SET_CART_FAILURE"
}

